### ISSUE TITLE
session_id problem : KeyError: 8873498640803430656

### ISSUE THREAD

**Issue by doudz** [jborean93/smbprotocol#193] opened 2022-10-03 12:28 UTC
I'm trying to use smbprotocol to connect to a AS400 share but I get the following error :

```
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smbclient
>>> smbclient.register_session('10.0.1.1', username='xxxxxx', password='xxxxxxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/vitanet_env/lib/python3.8/site-packages/smbclient/_pool.py", line 383, in register_session
    session.connect()
  File "/srv/vitanet_env/lib/python3.8/site-packages/smbprotocol/session.py", line 324, in connect
    self.connection.session_table[self.session_id] = self.connection.preauth_session_table.pop(self.session_id)
KeyError: 8873498640803430656
```

Could you help me to fix this ?

**Comment by jborean93** [comment] 2022-10-03 19:51
This is interesting, this happens just after the authentication attempt is completed but it seems like the pre authentication session id is not matching up with the final session id causing this key error. Is it possible for you to either send through a network capture or debug logs from `smbprotocol` of this failed exchange. This does technically have the authentication has and potentially some environment details so you are free to send it through to my email rather than posting it here. If you cannot do this then it would be great to know these 3 things on each of the message headers exchanged

* Command
* SessionId
* NT Status - this is only on the reply from the server

![image](https://user-images.githubusercontent.com/8462645/193666265-fe45a184-7ea6-4e11-bdc1-93e814a4af55.png)

**Comment by doudz** [comment] 2022-10-18 12:32
Soory I can't send a network capture.
below you'll find debug log

```
>>> smbclient.register_session('10.0.1.1', username='test', password='test')
INFO:smbprotocol.session:Initialising session with username: test
DEBUG:smbprotocol.session:Decoding SPNEGO token containing supported auth mechanisms
DEBUG:spnego._sspi:SSPI step input: YFgGBisGAQUFAqBOMEygGTAXBgkqhkiC9xIBAgIGCisGAQQBgjcCAgqjLzAtoCsbKUhPU1QvczY1NGYxM2Iudml0YWN1aXJlLmNvbUBWSVRBQ1VJUkUuQ09N
DEBUG:spnego._sspi:SSPI step output: YEgGBisGAQUFAqA+MDygDjAMBgorBgEEAYI3AgIKoioEKE5UTE1TU1AAAQAAALeCCOIAAAAAAAAAAAAAAAAAAAAACgBhSgAAAA8=
INFO:smbprotocol.session:Sending SMB2_SESSION_SETUP request message
INFO:smbprotocol.session:Receiving SMB2_SESSION_SETUP response message
DEBUG:smbprotocol.transport:Socket recv() returned 4 bytes (total 4)
DEBUG:smbprotocol.transport:Socket recv(351) (total 351)
DEBUG:smbprotocol.transport:Socket recv() returned 351 bytes (total 351)
DEBUG:smbprotocol.transport:Socket recv(4) (total 4)
INFO:smbprotocol.session:More processing is required for SMB2_SESSION_SETUP
DEBUG:spnego._sspi:SSPI step input: oYIBEzCCAQ+gAwoBAaEMBgorBgEEAYI3AgIKooH5BIH2TlRMTVNTUAACAAAAFAAUADoAAAAVgoridNTTNmsBWP0AAAAAAAAAAKgAqABOAAAABgGxHQAAAA8AAFYASQBUAEEAQwBVAEkAUgBFAAAAAQASAFEAUwA2ADUANABGADEAMwBCAAIAEgBWAEkAVABBAEMAVQBJAFIARQADACwAcwA2ADUANABmADEAMwBiAC4AdgBpAHQAYQBjAHUAaQByAGUALgBjAG8AbQAEABoAVgBJAFQAQQBDAFUASQBSAEUALgBDAE8ATQAFABoAVgBJAFQAQQBDAFUASQBSAEUALgBDAE8ATQAHAAgAAEqPZ+3i2AEAAAAA
DEBUG:spnego._sspi:SSPI step output: oYICETCCAg2gAwoBAaKCAfAEggHsTlRMTVNTUAADAAAAGAAYAH4AAABGAUYBlgAAABIAEgBYAAAACAAIAGoAAAAMAAwAcgAAABAAEADcAQAANYKI4goAYUoAAAAP8ZwK+Z0mYvg/5CaRLhdsPlYASQBUAEEAQwBVAEkAUgBFAHQAZQBzAHQAVgBBAEMAMAA3ADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3eDajJ1hpWt3KJfvEWO3dgEBAAAAAAAAAEqPZ+3i2AGUSeqTGQP3AAAAAAABABIAUQBTADYANQA0AEYAMQAzAEIAAgASAFYASQBUAEEAQwBVAEkAUgBFAAMALABzADYANQA0AGYAMQAzAGIALgB2AGkAdABhAGMAdQBpAHIAZQAuAGMAbwBtAAQAGgBWAEkAVABBAEMAVQBJAFIARQAuAEMATwBNAAUAGgBWAEkAVABBAEMAVQBJAFIARQAuAEMATwBNAAcACAAASo9n7eLYAQYABAACAAAACAAwADAAAAAAAAAAAAAAAAAgAADeoxyCDXhks6UVXzPx9EJR/YX041UijUgpTLY25nUqewoAEAAAAAAAAAAAAAAAAAAAAAAACQAaAGMAaQBmAHMALwAxADAALgAwAC4AMQAuADEAAAAAAAAAAACmhLTvoIfRtr1eyvKYlwjIoxIEEAEAAABv0tQqoT+/jQAAAAA=
INFO:smbprotocol.session:Sending SMB2_SESSION_SETUP request message
INFO:smbprotocol.session:Receiving SMB2_SESSION_SETUP response message
DEBUG:smbprotocol.transport:Socket recv() returned 4 bytes (total 4)
DEBUG:smbprotocol.transport:Socket recv(101) (total 101)
DEBUG:smbprotocol.transport:Socket recv() returned 101 bytes (total 101)
DEBUG:smbprotocol.transport:Socket recv(4) (total 4)
DEBUG:spnego._sspi:SSPI step input: oRswGaADCgEAoxIEEAEAAAD6WLDNY3GPqQAAAAA=
DEBUG:spnego._sspi:SSPI step output:
INFO:smbprotocol.session:Setting session id to 3619486725522326528
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\smbclient\_pool.py", line 383, in register_session
    session.connect()
  File "C:\Program Files\Python39\lib\site-packages\smbprotocol\session.py", line 324, in connect
    self.connection.session_table[self.session_id] = self.connection.preauth_session_table.pop(self.session_id)
KeyError: 3619486725522326528
```

**Comment by doudz** [comment] 2022-10-18 12:43
![image](https://user-images.githubusercontent.com/1262548/196432601-7b9c6791-c67c-4712-b3ea-31f1b788c33d.png)

**Comment by doudz** [comment] 2022-10-18 13:01
![image](https://user-images.githubusercontent.com/1262548/196436838-7680663e-4700-4e37-89b6-edd4b038fb4c.png)

**Comment by doudz** [comment] 2022-10-18 13:02
![image](https://user-images.githubusercontent.com/1262548/196437107-0fb9ce1f-87a5-4728-9bf7-30c54a815d0f.png)

**Comment by doudz** [comment] 2022-10-18 13:15
truncated log
![Uploading image.png…]()

**Comment by doudz** [comment] 2022-10-18 13:35
![image](https://user-images.githubusercontent.com/1262548/196444746-363bb2be-3888-4d43-bd5f-1aeadd4f40e4.png)

**Comment by jborean93** [comment] 2022-11-02 19:42
Ok I think I might understand what's going on. Can you share the the negotiated dialect was in the Negotiate Response.

![image](https://user-images.githubusercontent.com/8462645/199586168-1b4b39a9-04e2-48cc-9128-6777b6ed1aa3.png)

If it is 3.1.1 then the server isn't acting the way it should. The intermediate Session Setup Response with STATUS_MORE_PROCESSING_REQUIRED should have the session id allocated by the server which smbprotocol uses to track the messages for the pre auth hash calculation. It may be possible to still handle this but I would need to look at the code.

**Comment by doudz** [comment] 2022-11-07 11:20
I don't see any Negociate Protocol request or Negociate Protocol response in Wireshark
![image](https://user-images.githubusercontent.com/1262548/200298029-c80d9bd6-51c4-47ca-9f57-b38ef616f655.png)

**Comment by doudz** [comment] 2022-11-07 11:22
![image](https://user-images.githubusercontent.com/1262548/200298374-ec11cbf0-0909-496f-aadd-4be37e935e80.png)

**Comment by doudz** [comment] 2022-11-07 12:25
I tried to connect the shared folder using Windows and now Wireshark is catching a Negotiate Protocol Response

Looks like dialect is 2.0.2

![image](https://user-images.githubusercontent.com/1262548/200309763-0d3ec2cb-582c-4825-9ba5-4ec68f242bf7.png)

**Comment by doudz** [comment] 2022-11-07 12:55
I sent you the full debug log by email

**Comment by jborean93** [comment] 2022-11-08 10:48
Thanks for the info, I believe I understand what the problem is now and https://github.com/jborean93/smbprotocol/pull/203 should fix this issue for you. It would be great if you could test out the changes in that PR as I do not have a host I can test this scenario with to prove it works.

**Comment by doudz** [comment] 2022-11-08 11:01
I'm sorry but it doesn't work, now I have another error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sramage/.local/lib/python3.8/site-packages/smbclient/_pool.py", line 402, in register_session
    session.connect()
  File "/home/sramage/.local/lib/python3.8/site-packages/smbprotocol/session.py", line 393, in connect
    raise SMBException(
smbprotocol.exceptions.SMBException: SMB encryption or signing was required but session was authenticated as a guest which does not support encryption or signing
```

**Comment by jborean93** [comment] 2022-11-08 11:22
This error is raised by https://github.com/jborean93/smbprotocol/blob/a8853569790a5d973d2a9288d4860f32def8371a/src/smbprotocol/session.py#L393. It should only occur if the SESSION SETUP RESPONSE has the flags

* `SMB2_SESSION_FLAG_IS_GUEST` - If set, the client has been authenticated as a guest user.
* `SMB2_SESSION_FLAG_IS_NULL` - If set, the client has been authenticated as an anonymous user.

The connection is by default setup to require signing and because a guest or anon user do not have the required session context needed to sign or encrypt messages this fails. You can opt out of signing by registering the session first with `require_singing=False` like so

```python
smbclient.register_session('10.0.1.1', username='xxxxxx', password='xxxxxxx', require_signing=False)
```

You should really look into seeing if your server can support at least signing because this leaves you susceptible to man in the middle and relay attacks, hence why the default is True.

**Comment by jborean93** [comment] 2022-11-08 22:18
The fact that you got to that part shows the session is being created, you just now have another problem. As the original issue is fixed I'm closing the issue. If you do have any further problems please open a new issue and we can move forward from there.

**Closed** 2022-11-08 22:18 UTC
