### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by alp-yg** [jborean93/smbprotocol#48] opened 2020-08-31 15:33 UTC
Hi,

When doing some testing with your library, I happen to stumble onto a ConnectionResetError as follows:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbclient\_os.py", line 230, in listdir
    with SMBDirectoryIO(path, mode='r', share_access='r', **kwargs) as dir_fd:
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbclient\_io.py", line 295, in __enter__
    self.open()
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbclient\_io.py", line 334, in open
    open_result = self.fd.create(
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbprotocol\open.py", line 1207, in create
    request = self.connection.send(create,
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbprotocol\connection.py", line 965, in send
    return self._send([message], session_id=sid, tree_id=tid, message_id=message_id, credit_request=credit_request,
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbprotocol\connection.py", line 763, in wrapped
    return func(self, *args, **kwargs)
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbprotocol\connection.py", line 1251, in _send
    self.transport.send(send_data)
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbprotocol\transport.py", line 67, in wrapped
    func(self, *args, **kwargs)
  File "D:\Python\Anaconda3-2019.10\envs\test_env\lib\site-packages\smbprotocol\transport.py", line 108, in send
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

The funny thing is, it's never a problem the first time I try to use the smbclient, but it happens after some undetermined amount of time, which helps a lot in debugging /s
I manage to solve this problem by either restarting my Python shell, or by deleting the connection from the pool in `smbclient._pool._SMB_CONNECTIONS`. Note that I was able to find this second solution by trying to delete the connection and resetting the connection cache, and seeing that the code fails when trying to disconnect the connection, yet it still works as `smbclient._pool.delete_session` first deletes the connection from the pool then tries to disconnect it, while `smbclient._pool.reset_connection_cache` does it the other way around (might be an other issue that you should look into?).

I can manage with this weird solution, but it doesn't feel right, especially because I'm never closing the connection in the end. Do you have any idea where that could come from? My guess is that it's because I'm behind a proxy using Kerberos authentication, which should be invalidated after a certain amount of time, but I've been running the following code for almost 25min straight without any error, despite the error happening much quicker in other cases and Kerberos authentication supposedly running out after 15min max.

```
import smbclient
import time

start_time = time.perf_counter()

try:
    while True:
        smbclient.listdir(server)
except:
    pass

stop_time = time.perf_counter()

print("Elapsed time: {diff}s".format(diff=stop_time-start_time))
```

Thanks in advance for any help you could provide.

**Comment by adiroiban** [comment] 2020-08-31 15:49
Might be the same cause as #31

**Comment by alp-yg** [comment] 2020-08-31 16:25
That indeed looks a lot like my issue in its behaviour, except for its error returned, which doesn't seem central to the issue.
Thanks for pointing it out, I'll keep an eye on it and will try using register_session and delete_session tomorrow, and keep you updated.

**Comment by jborean93** [comment] 2020-09-01 21:39
Yea this is a duplicate of #31. Unfortunately I haven't had time to follow up on it and find a solution. Please keep track of that issue for any changes in the future.

**Closed by jborean93** 2020-09-01 21:39 UTC
